Name: Chanyu Choung

Class: CMP414

Homework due date: Mar 15th, 2021 (Monday)

# Week 6 Homework
This homework assignment will build three models on the advertising data and evaluate their performance. You can use tools from sklearn to complete this task.

Source of data:  https://www.statlearning.com/s/Advertising.csv

1. Use train_test_split to split the data into training set (80%) and test set (20%).

2. Build a multilinear regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_lr. Train the model on the training set and obtain model predictions on the test set.

3.  Build a degree 2 polynomial regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_pr2. Train the model on the training set and obtain model predictions on the test set.

4.  Build a degree 10 polynomial regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_pr10. Train the model on the training set and obtain model predictions on the test set.

5. Calculate the test MSE of each model using the mean_squared_error function. Which model gives the best MSE?

In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Importing the data frame
url = "https://www.statlearning.com/s/Advertising.csv"
data = pd.read_csv(url, index_col=0)

In [2]:
# Split the data into 80% training data and 20% test data.
from sklearn.model_selection import train_test_split
training_data, test_data = train_test_split(data, test_size=0.2)
test_data = test_data.copy()

In [3]:
# Initializing values
trainingX = training_data[["TV","radio","newspaper"]]
trainingY = training_data["sales"]
testX = test_data[["TV","radio","newspaper"]]
testY = test_data["sales"]

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

def get_Poly(n):
    poly_features = PolynomialFeatures(degree=n, include_bias=False)
    X_poly = poly_features.fit_transform(trainingX)
    X_polyT2 = poly_features.fit_transform(testX)
    return X_poly, X_polyT2

def get_Predict(X1, X2, Y1, Name):
    # Train the model on training set
    model = LinearRegression()
    model.fit(X1, Y1)
    print(model.coef_[:3], model.intercept_)

    # Obtain the model predictions
    test_data[Name] = model.predict(X2)
    print(test_data.head(), "\n")
    return model

# Multilinear Regression
model_lr = get_Predict(trainingX, testX, trainingY, "MLR")
# Polynomial-2 Regression
poly2, polyT2 = get_Poly(2)
model_pr2 = get_Predict(poly2, polyT2, trainingY, "PR2")
# Polynomial-10 Regression
poly10, polyT10 = get_Poly(10)
model_pr10 = get_Predict(poly10, polyT10, trainingY, "PR10")

[0.04490328 0.1923331  0.00308131] 2.7609259506115222
        TV  radio  newspaper  sales        MLR
74   129.4    5.7       31.3   11.0   9.764154
99   289.7   42.3       51.2   25.4  24.062858
4    151.5   41.3       58.5   18.5  17.687386
7     57.5   32.8       23.5   11.8  11.723801
148  243.2   49.0       44.3   25.4  23.242227 

[0.05144743 0.0139232  0.00617618] 5.146370827724629
        TV  radio  newspaper  sales        MLR        PR2
74   129.4    5.7       31.3   11.0   9.764154  10.915946
99   289.7   42.3       51.2   25.4  24.062858  25.390029
4    151.5   41.3       58.5   18.5  17.687386  18.647582
7     57.5   32.8       23.5   11.8  11.723801  10.745232
148  243.2   49.0       44.3   25.4  23.242227  25.707361 

[ 3.56407077e-12 -9.37041060e-13 -3.90278475e-12] 6.638132258400819
        TV  radio  newspaper  sales        MLR        PR2        PR10
74   129.4    5.7       31.3   11.0   9.764154  10.915946   14.559169
99   289.7   42.3       51.2   25.4  24.062858  25.

In [5]:
# Calculate MSE of each model
from sklearn.metrics import mean_squared_error
LR = model_lr

# MSE of Multilinear Regression 
theta = np.array([LR.intercept_, LR.coef_[0], LR.coef_[1], LR.coef_[2]])
list_errors = []

for i in data.index:
    x = np.array([1, data.loc[i, "TV"], data.loc[i, "radio"], data.loc[i, "newspaper"]])
    theta_dot_x = theta.dot(x)
    y = data.loc[i, "sales"]
    squared_error = (theta_dot_x - y) ** 2
    list_errors.append(squared_error)
print("Multilinear Regression MSE:", np.mean(list_errors))

# MSE of Polynomial-2 Regression
predictions_pr2 = model_pr2.predict(polyT2)
mse_pr2 = mean_squared_error(testY, predictions_pr2)
print("Polynomial Regression 2 MSE:", mse_pr2)

# MSE of Polynomial-10 Regression
predictions_pr10 = model_pr10.predict(polyT10)
mse_pr10 = mean_squared_error(testY, predictions_pr10)
print("Polynomial Regression 10 MSE:", mse_pr10)

Multilinear Regression MSE: 2.811266255099626
Polynomial Regression 2 MSE: 0.22111810420567551
Polynomial Regression 10 MSE: 160088.90246208335


Polynomial of degree 2 gives the least MSE output, which is the best outcome.