Name: Chanyu Choung

Class: CMP414

Homework due date: Mar 15th, 2021 (Monday)

# Week 6 Homework
This homework assignment will build three models on the advertising data and evaluate their performance. You can use tools from sklearn to complete this task.

Source of data:  https://www.statlearning.com/s/Advertising.csv

1. Use train_test_split to split the data into training set (80%) and test set (20%).

2. Build a multilinear regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_lr. Train the model on the training set and obtain model predictions on the test set.

3.  Build a degree 2 polynomial regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_pr2. Train the model on the training set and obtain model predictions on the test set.

4.  Build a degree 10 polynomial regression model with 'TV', 'Radio', and 'newspaper' as input variables and 'sales' as output variable. Name the model model_pr10. Train the model on the training set and obtain model predictions on the test set.

5. Calculate the test MSE of each model using the mean_squared_error function. Which model gives the best MSE?

In [ ]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Importing the data frame
url = "https://www.statlearning.com/s/Advertising.csv"
advertising = pd.read_csv(url, index_col=0)

In [ ]:
# Split the data into 80% training data and 20% test data.
from sklearn.model_selection import train_test_split
training_data, test_data = train_test_split(advertising, test_size=0.2)
test_data = test_data.copy()

In [ ]:
# Initializing values
X1 = advertising[["TV","radio","newspaper"]]
Y1 = advertising["sales"]
X2 = test_data[["TV","radio","newspaper"]]
Y2 = test_data["sales"]

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

def get_Poly(n):
    poly_features = PolynomialFeatures(degree=n, include_bias=False)
    X_poly = poly_features.fit_transform(X2)
    return X_poly

def get_Predict(X, X2, Y, Name):
    # Train the model on training set
    model = LinearRegression()
    model.fit(X, Y)
    print(model.coef_[:3], model.intercept_)

    # Obtain the model predictions
    predictions = model.predict(X2)
    test_data[Name] = predictions
    print(test_data.head(), "\n")
    return model

# Multilinear Regression
MLR = get_Predict(X1, X2, Y1, "MLR")
# Polynomial-2 Regression
Poly2 = get_Poly(2)
PR2 = get_Predict(Poly2, Poly2, Y2, "PR2")
# Polynomial-10 Regression
Poly10 = get_Poly(10)
PR10 = get_Predict(Poly10, Poly10, Y2, "PR10")

[ 0.04576465  0.18853002 -0.00103749] 2.938889369459412
        TV  radio  newspaper  sales        MLR        PR2  PR10
93   217.7   33.5       59.0   19.4  19.156396  19.770318  19.4
80   116.0    7.7       23.1   11.0   9.675303  10.892426  11.0
159   11.7   36.9       45.2    7.3  10.384199   7.944791   7.3
174  168.4    7.1       12.8   11.7  11.970939  11.966313  11.7
3     17.2   45.9       69.3    9.3  12.307671   8.898595   9.3 

[3.45320599e-02 2.92561282e-05 4.20297512e-03] 6.7550325644375215
        TV  radio  newspaper  sales        MLR        PR2  PR10
93   217.7   33.5       59.0   19.4  19.156396  19.770318  19.4
80   116.0    7.7       23.1   11.0   9.675303  10.892426  11.0
159   11.7   36.9       45.2    7.3  10.384199   7.944791   7.3
174  168.4    7.1       12.8   11.7  11.970939  11.966313  11.7
3     17.2   45.9       69.3    9.3  12.307671   8.898595   9.3 

[-1.41766495e-19  1.09845544e-21 -4.12007220e-24] 8.810517122133792
        TV  radio  newspaper  sales   

In [ ]:
# Calculate MSE of each model
from sklearn.metrics import mean_squared_error

# MSE of Multilinear Regression 
theta = np.array([MLR.intercept_, MLR.coef_[0], MLR.coef_[1], MLR.coef_[2]])
list_errors = []

for i in advertising.index:
    x = np.array([1, advertising.loc[i, "TV"], advertising.loc[i, "radio"], advertising.loc[i, "newspaper"]])
    theta_dot_x = theta.dot(x)
    y = advertising.loc[i, "sales"]
    squared_error = (theta_dot_x - y) ** 2
    list_errors.append(squared_error)
print("Multilinear Regression MSE:", np.mean(list_errors))

# MSE of Polynomial-2 Regression
predictions_pr2 = PR2.predict(Poly2)
MSE_pr2 = mean_squared_error(Y2, predictions_pr2)
print("Polynomial Regression 2 MSE:", MSE_pr2)

# MSE of Polynomial-10 Regression
predictions_pr10 = PR10.predict(Poly10)
MSE_pr10 = mean_squared_error(Y2, predictions_pr10)
print("Polynomial Regression 10 MSE:", MSE_pr10)

Multilinear Regression MSE: 2.784126314510936
Polynomial Regression 2 MSE: 0.08623448258920496
Polynomial Regression 10 MSE: 2.114671631902726e-18
